#!/bin/bash

echo "🚀 EchoChat Render 快速部署腳本"
echo "================================"

# 檢查 Git 狀態
echo "📋 檢查 Git 狀態..."
if [ -n "$(git status --porcelain)" ]; then
    echo "⚠️  有未提交的更改，正在提交..."
    git add .
    git commit -m "自動部署更新: $(date)"
fi

# 推送到 GitHub
echo "📤 推送到 GitHub..."
git push origin main

echo ""
echo "✅ 代碼已推送到 GitHub"
echo ""
echo "🎯 下一步部署步驟："
echo ""
echo "📋 後端部署 (echochat-api):"
echo "1. 前往 https://render.com"
echo "2. 點擊 'New +' → 'Web Service'"
echo "3. 連接您的 GitHub 倉庫: https://github.com/IAN1215/AI-CHATBOT"
echo "4. 設定："
echo "   - Name: echochat-backend"
echo "   - Root Directory: echochat-api"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Plan: Free"
echo ""
echo "🔧 環境變量設定："
echo "在 Render 控制台中設定以下環境變量："
echo "- NODE_ENV: production"
echo "- JWT_SECRET: [自動生成]"
echo "- PORT: 10000"
echo "- DATA_DIR: /opt/render/project/src/data"
echo "- LINE_CHANNEL_ACCESS_TOKEN: [您的 Line Token]"
echo "- LINE_CHANNEL_SECRET: [您的 Line Secret]"
echo "- OPENAI_API_KEY: [您的 OpenAI Key]"
echo ""
echo "📋 前端部署選項："
echo ""
echo "選項 1: Vercel (推薦)"
echo "1. 前往 https://vercel.com"
echo "2. 使用 GitHub 帳號登入"
echo "3. 點擊 'New Project'"
echo "4. 選擇您的 GitHub 倉庫"
echo "5. 設定專案名稱：echochat-frontend"
echo "6. 點擊 'Deploy'"
echo ""
echo "選項 2: Render Static Site"
echo "1. 前往 https://render.com"
echo "2. 點擊 'New +' → 'Static Site'"
echo "3. 連接您的 GitHub 倉庫"
echo "4. 設定："
echo "   - Name: echochat-frontend"
echo "   - Root Directory: ./"
echo "   - Build Command: echo 'Build completed'"
echo "   - Publish Directory: public"
echo ""
echo "🔍 部署後檢查："
echo "1. 後端 API: https://echochat-api.onrender.com/api/health"
echo "2. 前端: 您的前端 URL"
echo "3. 測試登入: sunnyharry1 / gele1227"
echo ""
echo "📖 詳細指南請查看: RENDER_DEPLOYMENT_GUIDE.md" 